### ISSUE TITLE
Getting error when starting openGallery 

### ISSUE THREAD

**Issue by dimovdaniel** [prashantsaini1/titanium-android-imagepicker#17]
Hello. I'm getting the following error. 
```
9-07-24 11:32:10.948 1825-2518/? I/ActivityManager: START u0 {cmp=com.sav/ti.imagepicker.ImageViewerActivity (has extras)} from uid 10085
2019-07-24 11:32:10.949 1572-3769/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 4998365 , only wrote 4998240
2019-07-24 11:32:11.015 6371-6371/? W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@cbd59ad
2019-07-24 11:32:11.060 1582-1582/? D/gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 8298496
2019-07-24 11:32:11.077 1582-1582/? I/chatty: uid=1000(system) allocator@2.0-s identical 1 line
2019-07-24 11:32:11.092 1582-1582/? D/gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 8298496
2019-07-24 11:32:11.112 6371-6371/? D/AndroidRuntime: Shutting down VM




2019-07-24 11:32:11.114 6371-6371/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sav, PID: 6371
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
        at android.view.LayoutInflater.from(LayoutInflater.java:229)
        at ti.imagepicker.ImageViewerActivity$PhotoAdapter.onCreateViewHolder(ImageViewerActivity.java:254)
        at ti.imagepicker.ImageViewerActivity$PhotoAdapter.onCreateViewHolder(ImageViewerActivity.java:245)
        at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6685)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5869)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
        at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
        at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:443)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:753)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2792)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2319)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
2019-07-24 11:32:11.114 6371-6371/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by dimovdaniel** [comment]
My Code is simple, as in the example
Using 8.0.2 GA 
```
var gallerypicker = require('ti.imagepicker');
gallerypicker.openGallery({
	  callback : function (e) {
	    if (e.success) {
	      var allImages = e.images;
	    } else if (e.cancel) {
	      // gallery result cancelled
	    } else {
	      alert(e.message);
	    }
	  }
	});
```

**Comment by prashantsaini1** [comment]
@dimovdaniel can you mention the reason of closing this issue to let other users know its solution?
